services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    command: ["./lib"]
  db:
    image: redis:7.4-alpine
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${DB_PASSWORD}
      - REDIS_DB=9
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis-db:/var/lib/redis/data

volumes:
  redis-db: